INSERT INTO pais (paisid, iso3, nombre, nombre_ingles, codigo_numerico, prefijo_telefono, continente, activo) VALUES
('AD', 'AND', 'Andorra', 'Andorra', 20, '+376', 'Europa', TRUE),
('ES', 'ESP', 'España', 'Spain', 724, '+34', 'Europa', TRUE);


INSERT INTO provincia (provinciaid, nombre, paisid) VALUES
('01', 'Araba/Álava', 'ES'),
('02', 'Albacete', 'ES'),
('03', 'Alicante/Alacant', 'ES'),
('04', 'Almería', 'ES'),
('05', 'Ávila', 'ES'),
('06', 'Badajoz', 'ES'),
('07', 'Illes Balears', 'ES'),
('08', 'Barcelona', 'ES'),
('09', 'Burgos', 'ES'),
('10', 'Cáceres', 'ES'),
('11', 'Cádiz', 'ES'),
('12', 'Castellón/Castelló', 'ES'),
('13', 'Ciudad Real', 'ES'),
('14', 'Córdoba', 'ES'),
('15', 'A Coruña', 'ES'),
('16', 'Cuenca', 'ES'),
('17', 'Girona', 'ES'),
('18', 'Granada', 'ES'),
('19', 'Guadalajara', 'ES'),
('20', 'Gipuzkoa', 'ES'),
('21', 'Huelva', 'ES'),
('22', 'Huesca', 'ES'),
('23', 'Jaén', 'ES'),
('24', 'León', 'ES'),
('25', 'Lleida', 'ES'),
('26', 'La Rioja', 'ES'),
('27', 'Lugo', 'ES'),
('28', 'Madrid', 'ES'),
('29', 'Málaga', 'ES'),
('30', 'Murcia', 'ES'),
('31', 'Navarra', 'ES'),
('32', 'Ourense', 'ES'),
('33', 'Asturias', 'ES'),
('34', 'Palencia', 'ES'),
('35', 'Las Palmas', 'ES'),
('36', 'Pontevedra', 'ES'),
('37', 'Salamanca', 'ES'),
('38', 'Santa Cruz de Tenerife', 'ES'),
('39', 'Cantabria', 'ES'),
('40', 'Segovia', 'ES'),
('41', 'Sevilla', 'ES'),
('42', 'Soria', 'ES'),
('43', 'Tarragona', 'ES'),
('44', 'Teruel', 'ES'),
('45', 'Toledo', 'ES'),
('46', 'Valencia/València', 'ES'),
('47', 'Valladolid', 'ES'),
('48', 'Bizkaia', 'ES'),
('49', 'Zamora', 'ES'),
('50', 'Zaragoza', 'ES'),
('51', 'Ceuta', 'ES'),
('52', 'Melilla', 'ES');


